<?php

declare(strict_types=1);

$start = microtime(true);

$source = __DIR__ . '/src';
$output = __DIR__ . '/framework/Base8.php';

if (!is_dir($source)) {
    exit('Missing source directory.');
}

$files = glob($source . '/*.php');

if ($files === false || $files === []) {
    exit('No PHP files found.');
}

sort($files, SORT_STRING);

$header = <<<'PHP'
<?php

declare(strict_types=1);

PHP;

$buildTime = date('Y-m-d H:i:s');

$build = <<<PHP
<?php

/*
|--------------------------------------------------------------------------
| Base8 Framework
|--------------------------------------------------------------------------
|
| This file is automatically generated.
|
| Build time: {$buildTime}
|
| Do not edit this file manually.
|
*/

declare(strict_types=1);

PHP;

foreach ($files as $file) {

    $code = file_get_contents($file);

    if ($code === false) {
        exit("Cannot read {$file}.");
    }

    if (str_starts_with($code, "\xEF\xBB\xBF")) {
        exit("UTF-8 BOM is not allowed: {$file}");
    }

    if (!str_starts_with($code, $header)) {

        exit(
            "Invalid source file: {$file}\n\n" .
            "Every source file must begin with:\n\n" .
            "<?php\n\n" .
            "declare(strict_types=1);\n"
        );
    }

    $code = substr($code, strlen($header));

    $build .= rtrim($code) . PHP_EOL . PHP_EOL;
}

$build = rtrim($build) . PHP_EOL;

if (file_put_contents($output, $build) === false) {
    exit("Cannot write {$output}");
}

$duration = number_format(
    (microtime(true) - $start) * 1000,
    2
);

$size = number_format(
    filesize($output) / 1024,
    2
);

$count = count($files);

if (PHP_SAPI === 'cli') {

    echo PHP_EOL;
    echo "======================================================" . PHP_EOL;
    echo "                 Base8 Framework Builder" . PHP_EOL;
    echo "======================================================" . PHP_EOL;
    echo PHP_EOL;
    echo " Source       : src" . PHP_EOL;
    echo " Output       : Base8.php" . PHP_EOL;
    echo " Files        : {$count}" . PHP_EOL;
    echo " Output size  : {$size} KB" . PHP_EOL;
    echo " Build time   : {$buildTime}" . PHP_EOL;
    echo " Duration     : {$duration} ms" . PHP_EOL;
    echo PHP_EOL;
    echo " Status       : SUCCESS" . PHP_EOL;
    echo PHP_EOL;
    echo "======================================================" . PHP_EOL;

    exit();
}

header('Content-Type: text/html; charset=utf-8');

?>
<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">

    <title>Base8 Builder</title>

    <style>

        body {
            margin: 40px;
            background: #f5f5f5;
            color: #222;
            font: 15px Consolas, Monaco, monospace;
        }

        .card {
            max-width: 720px;
            background: #fff;
            border: 1px solid #ddd;
            padding: 24px;
        }

        h1 {
            margin: 0 0 24px;
            font-size: 24px;
        }

        table {
            width: 100%;
            border-collapse: collapse;
        }

        td {
            padding: 8px 0;
        }

        td:first-child {
            width: 180px;
            font-weight: bold;
        }

        .success {
            margin-top: 24px;
            color: #198754;
            font-weight: bold;
        }

    </style>

</head>

<body>

<div class="card">

    <h1>Base8 Framework Builder</h1>

    <table>

        <tr>
            <td>Source</td>
            <td>src</td>
        </tr>

        <tr>
            <td>Output</td>
            <td>Base8.php</td>
        </tr>

        <tr>
            <td>Files</td>
            <td><?= $count ?></td>
        </tr>

        <tr>
            <td>Output size</td>
            <td><?= $size ?> KB</td>
        </tr>

        <tr>
            <td>Build time</td>
            <td><?= $buildTime ?></td>
        </tr>

        <tr>
            <td>Duration</td>
            <td><?= $duration ?> ms</td>
        </tr>

    </table>

    <p class="success">✔ Build completed successfully.</p>

</div>

</body>

</html>