<?php

/*
|--------------------------------------------------------------------------
| Base8 Framework
|--------------------------------------------------------------------------
|
| This file is automatically generated.
|
| Build time: 2026-07-19 19:23:51
|
| Do not edit this file manually.
|
*/

declare(strict_types=1);

namespace Base8 {

    final class Base8
    {
        /**
         * Framework version.
         */
        public const VERSION = '1.1.1';

        /**
         * Minimum supported PHP version.
         */
        public const MIN_PHP_VERSION = 80000;

        /**
         * Application root directory.
         */
        private static string $root;

        /**
         * Framework entry point.
         *
         * @param string $root
         *     Absolute path to the application root directory.
         */
        public static function run(string $root): void
        {
            if (PHP_VERSION_ID < self::MIN_PHP_VERSION) {
                throw new \RuntimeException(
                    'Base8 requires PHP 8.0 or newer.'
                );
            }

            $root = realpath($root);

            if ($root === false || !is_dir($root)) {
                throw new \RuntimeException(
                    'Invalid public directory.'
                );
            }

            $root = dirname(rtrim($root, '/\\')) . DIRECTORY_SEPARATOR . 'app';

            if (!is_dir($root)) {
                throw new \RuntimeException(
                    'Application directory not found.'
                );
            }

            self::$root = $root;

            $module = 'index';
            $action = 'index';
            $params = [];

            $path = parse_url(
                $_SERVER['REQUEST_URI'] ?? '/',
                PHP_URL_PATH
            ) ?? '/';

            $base = rtrim(
                dirname($_SERVER['SCRIPT_NAME'] ?? ''),
                '/\\'
            );

            if (
                $base !== '' &&
                $base !== '/' &&
                str_starts_with($path, $base)
            ) {
                $path = substr($path, strlen($base));
            }

            $uri = trim($path, '/');

            if (strlen($uri) > 2048) {
                self::error(414);
            }

            if ($uri !== '') {

                $segments = explode('/', $uri);

                $module = strtolower($segments[0]);

                if (!self::isValidRouteSegment($module)) {
                    self::error(404);
                }

                if (isset($segments[1])) {

                    $action = strtolower($segments[1]);

                    if (!self::isValidRouteSegment($action)) {
                        self::error(404);
                    }

                    if (str_contains($action, '-')) {

                        $parts = explode('-', $action);

                        $action = array_shift($parts);

                        foreach ($parts as $part) {
                            $action .= ucfirst($part);
                        }
                    }

                    if (isset($segments[2])) {
                        $params = array_slice($segments, 2);
                    }
                }
            }

            $file = self::$root . "/modules/$module.php";

            if (!is_file($file)) {
                self::error($module === 'index' ? 500 : 404);
            }

            require $file;

            if (!function_exists($action)) {
                self::error($module === 'index' ? 500 : 404);
            }

            $action(...$params);
        }

        /**
         * Returns the application root directory.
         *
         * @return string
         *     Absolute path to the application root directory.
         */
        public static function root(): string
        {
            return self::$root;
        }

        /**
         * Validates a route segment.
         *
         * @param string $segment
         *     Route segment.
         *
         * @return bool
         *     True if the segment is valid, otherwise false.
         */
        private static function isValidRouteSegment(string $segment): bool
        {
            if ($segment === '' || $segment[0] === '_') {
                return false;
            }

            $length = strlen($segment);

            for ($i = 0; $i < $length; $i++) {

                $char = ord($segment[$i]);

                if (
                    ($char >= 48 && $char <= 57) ||
                    ($char >= 65 && $char <= 90) ||
                    ($char >= 97 && $char <= 122) ||
                    $char === 45
                ) {
                    continue;
                }

                return false;
            }

            return true;
        }

        /**
         * Terminates the current request with the specified HTTP status code.
         *
         * @param int $code
         *     HTTP status code.
         *
         * @return never
         */
        private static function error(int $code): never
        {
            http_response_code($code);

            $file = self::$root . "/errors/$code.php";

            if (is_file($file)) {
                require $file;
            }

            exit();
        }
    }

}


namespace {


/**
 * Sets a cookie.
 *
 * @param string $name
 *     Cookie name.
 *
 * @param string $value
 *     Cookie value.
 *
 * @param int $expires
 *     Cookie lifetime in seconds.
 *     Set to 0 for a session cookie.
 *
 * @param string $path
 *     Cookie path.
 *
 * @param string $domain
 *     Cookie domain.
 *
 * @param bool|null $secure
 *     Whether the cookie should be sent only over HTTPS.
 *     If null, the current request protocol is used.
 *
 * @param bool $httpOnly
 *     Whether the cookie is accessible only through HTTP.
 *
 * @param string $sameSite
 *     SameSite policy.
 *     Allowed values: Lax, Strict, None.
 *
 * @return bool
 *     True on success, otherwise false.
 */
function b8_cookie_set(
    string $name,
    string $value,
    int $expires = 0,
    string $path = '/',
    string $domain = '',
    ?bool $secure = null,
    bool $httpOnly = true,
    string $sameSite = 'Lax'
): bool {

    $secure ??= b8_https();

    return setcookie(
        $name,
        $value,
        [
            'expires' => $expires > 0
                ? time() + $expires
                : 0,
            'path' => $path,
            'domain' => $domain,
            'secure' => $secure,
            'httponly' => $httpOnly,
            'samesite' => $sameSite,
        ]
    );
}

/**
 * Returns a cookie value.
 *
 * @param string $name
 *     Cookie name.
 *
 * @param mixed $default
 *     Value returned if the cookie does not exist.
 *
 * @return mixed
 *     Cookie value or the default value.
 */
function b8_cookie_get(
    string $name,
    mixed $default = null
): mixed
{
    return $_COOKIE[$name] ?? $default;
}

/**
 * Deletes a cookie.
 *
 * @param string $name
 *     Cookie name.
 *
 * @param string $path
 *     Cookie path.
 *
 * @param string $domain
 *     Cookie domain.
 *
 * @param bool|null $secure
 *     Whether the cookie should be sent only over HTTPS.
 *     If null, the current request protocol is used.
 *
 * @return bool
 *     True on success, otherwise false.
 */
function b8_cookie_delete(
    string $name,
    string $path = '/',
    string $domain = '',
    ?bool $secure = null
): bool {

    $secure ??= b8_https();

    unset($_COOKIE[$name]);

    return setcookie(
        $name,
        '',
        [
            'expires' => time() - 3600,
            'path' => $path,
            'domain' => $domain,
            'secure' => $secure,
            'httponly' => true,
            'samesite' => 'Lax',
        ]
    );
}


/**
 * Encrypts a string using AES-256-CBC.
 *
 * The encrypted value is authenticated using HMAC-SHA256 and
 * returned as a Base64-encoded string suitable for storage in
 * cookies, sessions, JSON, databases, or HTML.
 *
 * The encryption key must be generated using b8_key().
 *
 * @param string $plaintext
 *     Plain text to encrypt.
 *
 * @param string $key
 *     Base64-encoded encryption key.
 *
 * @return string
 *     Base64-encoded encrypted string.
 *
 * @throws \InvalidArgumentException
 *     If the encryption key is invalid.
 *
 * @throws \RuntimeException
 *     If encryption fails.
 */
function b8_encrypt(string $plaintext, string $key): string
{
    $key = base64_decode($key, true);

    if ($key === false || strlen($key) !== 32) {
        throw new \InvalidArgumentException(
            'Invalid encryption key.'
        );
    }

    $cipher = 'AES-256-CBC';

    $ivLength = openssl_cipher_iv_length($cipher);

    $iv = random_bytes($ivLength);

    $ciphertext = openssl_encrypt(
        $plaintext,
        $cipher,
        $key,
        OPENSSL_RAW_DATA,
        $iv
    );

    if ($ciphertext === false) {
        throw new \RuntimeException(
            'Unable to encrypt data.'
        );
    }

    $hmac = hash_hmac(
        'sha256',
        $ciphertext,
        $key,
        true
    );

    return base64_encode(
        $iv . $hmac . $ciphertext
    );
}

/**
 * Decrypts a string previously encrypted by b8_encrypt().
 *
 * The HMAC is verified before the decrypted value is returned.
 *
 * The encryption key must be generated using b8_key().
 *
 * @param string $encrypted
 *     Base64-encoded encrypted string.
 *
 * @param string $key
 *     Base64-encoded encryption key.
 *
 * @return string|false
 *     Original plaintext or false if authentication or
 *     decryption fails.
 *
 * @throws \InvalidArgumentException
 *     If the encryption key is invalid.
 */
function b8_decrypt(string $encrypted, string $key): string|false
{
    $key = base64_decode($key, true);

    if ($key === false || strlen($key) !== 32) {
        throw new \InvalidArgumentException(
            'Invalid encryption key.'
        );
    }

    $cipher = 'AES-256-CBC';

    $ivLength = openssl_cipher_iv_length($cipher);

    $hmacLength = 32;

    $data = base64_decode($encrypted, true);

    if ($data === false) {
        return false;
    }

    if (strlen($data) < $ivLength + $hmacLength) {
        return false;
    }

    $iv = substr($data, 0, $ivLength);

    $hmac = substr(
        $data,
        $ivLength,
        $hmacLength
    );

    $ciphertext = substr(
        $data,
        $ivLength + $hmacLength
    );

    $calculated = hash_hmac(
        'sha256',
        $ciphertext,
        $key,
        true
    );

    if (!hash_equals($hmac, $calculated)) {
        return false;
    }

    $plaintext = openssl_decrypt(
        $ciphertext,
        $cipher,
        $key,
        OPENSSL_RAW_DATA,
        $iv
    );

    return $plaintext === false
        ? false
        : $plaintext;
}

/**
 * Generates a cryptographically secure encryption key.
 *
 * The returned key is Base64 encoded and intended for use with
 * b8_encrypt() and b8_decrypt().
 *
 * @return string
 *     Base64-encoded 256-bit encryption key.
 *
 * @throws \Exception
 *     If a secure random source is unavailable.
 */
function b8_key(): string
{
    return base64_encode(
        random_bytes(32)
    );
}

/**
 * Generates an RFC 4122 version 4 UUID.
 *
 * @param string|null $data
 *     Optional 16-byte binary seed.
 *
 * @return string
 *     UUID version 4.
 *
 * @throws \InvalidArgumentException
 *     If the supplied seed is not exactly 16 bytes.
 */
function b8_uuid(?string $data = null): string
{
    $data ??= random_bytes(16);

    if (strlen($data) !== 16) {
        throw new \InvalidArgumentException(
            'UUID seed must contain exactly 16 bytes.'
        );
    }

    $data[6] = chr(
        (ord($data[6]) & 0x0f) | 0x40
    );

    $data[8] = chr(
        (ord($data[8]) & 0x3f) | 0x80
    );

    return vsprintf(
        '%s%s-%s-%s-%s-%s%s%s',
        str_split(bin2hex($data), 4)
    );
}


/**
 * Returns a GET parameter or the entire GET array.
 *
 * @param string|null $key
 *     GET parameter name.
 *     If null, the entire GET array is returned.
 *
 * @param mixed $default
 *     Value returned when the parameter does not exist.
 *
 * @return mixed
 *     GET parameter value, the default value, or the entire GET array.
 */
function b8_get(?string $key = null, mixed $default = null): mixed
{
    if ($key === null) {
        return $_GET;
    }

    return $_GET[$key] ?? $default;
}

/**
 * Returns a POST parameter or the entire POST array.
 *
 * @param string|null $key
 *     POST parameter name.
 *     If null, the entire POST array is returned.
 *
 * @param mixed $default
 *     Value returned when the parameter does not exist.
 *
 * @return mixed
 *     POST parameter value, the default value, or the entire POST array.
 */
function b8_post(?string $key = null, mixed $default = null): mixed
{
    if ($key === null) {
        return $_POST;
    }

    return $_POST[$key] ?? $default;
}

/**
 * Returns request data based on the current HTTP method.
 *
 * GET requests use the GET array.
 * POST requests use the POST array.
 *
 * @param string|null $key
 *     Request parameter name.
 *     If null, the entire request array is returned.
 *
 * @param mixed $default
 *     Value returned when the parameter does not exist.
 *
 * @return mixed
 *     Request parameter value, the default value, or the entire request array.
 */
function b8_request(?string $key = null, mixed $default = null): mixed
{
    if (b8_method('POST')) {
        return b8_post($key, $default);
    }

    return b8_get($key, $default);
}

/**
 * Returns the current HTTP request method or compares it.
 *
 * @param string|null $method
 *     HTTP method to compare (GET, POST, PUT, PATCH, DELETE, etc.).
 *     If null, the current request method is returned.
 *
 * @return string|bool
 *     Returns the current HTTP request method when no argument is supplied.
 *     Otherwise returns true if the supplied method matches the current
 *     request method, or false if it does not.
 */
function b8_method(?string $method = null): string|bool
{
    $current = $_SERVER['REQUEST_METHOD'] ?? 'CLI';

    if ($method === null) {
        return $current;
    }

    return strtoupper($method) === strtoupper($current);
}


/**
 * Sets the HTTP response status code.
 *
 * @param int $code
 *     HTTP response status code.
 *
 * @return void
 */
function b8_status(int $code): void
{
    http_response_code($code);
}

/**
 * Redirects the client to another URL.
 *
 * @param string $url
 *     Destination URL.
 *
 * @param int $code
 *     HTTP redirect status code.
 *
 * @return never
 */
function b8_redirect(string $url, int $code = 302): never
{
    http_response_code($code);

    header("Location: {$url}");

    exit();
}

/**
 * Sends a JSON response.
 *
 * @param mixed $data
 *     Data to encode as JSON.
 *
 * @param int $code
 *     HTTP response status code.
 *
 * @param int $flags
 *     Additional JSON encoding flags.
 *
 * @return never
 *
 * @throws JsonException
 */
function b8_json(
    mixed $data,
    int $code = 200,
    int $flags = 0
): never {
    http_response_code($code);

    header('Content-Type: application/json; charset=utf-8');

    echo json_encode(
        $data,
        JSON_THROW_ON_ERROR | $flags
    );

    exit();
}


/**
 * Starts a session.
 *
 * If the session is already active, this function does nothing.
 *
 * @return bool
 *     True on success, otherwise false.
 */
function b8_session_start(): bool
{
    if (session_status() === PHP_SESSION_ACTIVE) {
        return true;
    }

    return session_start([
        'use_strict_mode' => true,
        'use_only_cookies' => true,
        'cookie_httponly' => true,
        'cookie_samesite' => 'Lax',
        'cookie_secure' => b8_https(),
    ]);
}

/**
 * Stores a value in the session.
 *
 * The session is started automatically if necessary.
 *
 * @param string $key
 *     Session key.
 *
 * @param mixed $value
 *     Session value.
 *
 * @return void
 */
function b8_session_set(
    string $key,
    mixed $value
): void
{
    b8_session_start();

    $_SESSION[$key] = $value;
}

/**
 * Returns a session value.
 *
 * The session is started automatically if necessary.
 *
 * @param string $key
 *     Session key.
 *
 * @param mixed $default
 *     Value returned if the key does not exist.
 *
 * @return mixed
 *     Session value or the default value.
 */
function b8_session_get(
    string $key,
    mixed $default = null
): mixed
{
    b8_session_start();

    return $_SESSION[$key] ?? $default;
}

/**
 * Deletes a session value.
 *
 * The session is started automatically if necessary.
 *
 * @param string $key
 *     Session key.
 *
 * @return void
 */
function b8_session_delete(string $key): void
{
    b8_session_start();

    unset($_SESSION[$key]);
}

/**
 * Destroys the current session.
 *
 * If no session exists, this function succeeds.
 *
 * @return bool
 *     True on success, otherwise false.
 */
function b8_session_destroy(): bool
{
    if (session_status() !== PHP_SESSION_ACTIVE) {
        return true;
    }

    $_SESSION = [];

    if (ini_get('session.use_cookies')) {

        $params = session_get_cookie_params();

        setcookie(
            session_name(),
            '',
            [
                'expires' => time() - 3600,
                'path' => $params['path'],
                'domain' => $params['domain'],
                'secure' => $params['secure'],
                'httponly' => $params['httponly'],
                'samesite' => $params['samesite'] ?? 'Lax',
            ]
        );
    }

    return session_destroy();
}


/**
 * Returns the framework version.
 *
 * @return string
 *     Current Base8 version.
 */
function b8_version(): string
{
    return \Base8\Base8::VERSION;
}

/**
 * Returns the application root directory.
 *
 * @return string
 *     Absolute path to the application directory.
 */
function b8_root(): string
{
    return \Base8\Base8::root();
}

/**
 * Determines whether the current request uses HTTPS.
 *
 * @return bool
 *     True if the request uses HTTPS, otherwise false.
 */
function b8_https(): bool
{
    if (!empty($_SERVER['HTTPS']) && $_SERVER['HTTPS'] !== 'off') {
        return true;
    }

    return (
        ($_SERVER['HTTP_X_FORWARDED_PROTO'] ?? '') === 'https'
    );
}


/**
 * Renders a view.
 *
 * The view is loaded from the application's `views/` directory.
 * Variables supplied in `$data` are extracted into the local symbol table.
 *
 * @param string $view
 *     View name relative to the `views/` directory.
 *     Do not include the `.php` extension.
 *
 * @param array $data
 *     Variables available inside the view.
 *
 * @return never
 */
function b8_view(string $view, array $data = []): never
{
    if (
        $view === '' ||
        str_contains($view, '..') ||
        str_contains($view, '\\') ||
        str_contains($view, "\0")
    ) {
        b8_status(404);
        exit();
    }

    $file = b8_root() . "/views/{$view}.php";

    if (!is_file($file)) {
        b8_status(404);
        exit();
    }

    extract($data, EXTR_SKIP);

    require $file;

    exit();
}


}
